export const warns=[
    {
        id:"1",
        img:"/src/assets/img/mask.png",
        text:"配戴口罩"        
    },
    {
        id:"2",
        img:"/src/assets/img/smoke.png",
        text:"禁止吸菸"        
    },
    {
        id:"3",
        img:"/src/assets/img/dangerous.png",
        text:"禁止危險物品"        
    },
    {
        id:"4",
        img:"/src/assets/img/trash.png",
        text:"請勿亂丟垃圾"        
    },
    {
        id:"5",
        img:"/src/assets/img/running.png",
        text:"請勿奔跑、喧嘩"        
    }
]

export const videos=[
    {
        id:"1",
        img:"https://fakeimg.pl/300/",
        name:"test",
        text:"內容介紹"        
    },
    {
        id:"2",
        img:"https://fakeimg.pl/300/",
        name:"test",
        text:"內容介紹"        
    },
    {
        id:"3",
        img:"https://fakeimg.pl/300/",
        name:"test",
        text:"內容介紹"        
    },
    {
        id:"4",
        img:"https://fakeimg.pl/300/",
        name:"test",
        text:"內容介紹"        
    },
]