export const groups=[
    {
        id:"1",
        img:"/src/assets/img/market.png",
        name:"行銷組",
        text:"針對單一主題性的規劃行銷，"+"\n"+"以視覺設計及行銷概念作為展出內容。"
    },
    {
        id:"2",
        img:"/src/assets/img/animation.png",
        name:"影視組",
        text:"由動畫短片及劇情短片"+"\n"+"共同舉辦小型的影展輪播。"
    },
    {
        id:"3",
        img:"/src/assets/img/interact.png",
        name:"互動組",
        text:"結合程式設計開發互動裝置，"+"\n"+"使觀展人親身參與並體驗其中的樂趣。"        
    },
    {
        id:"4",
        img:"/src/assets/img/game.png",
        name:"遊戲組",
        text:"除了傳統的 PC遊戲外，"+"\n"+"還會以2D、3D的呈現手法"+"\n"+"製作多元類型的遊戲。"        
    }
]

export const classes=[
    {
        id:"1",
        name:"設計組",
        text:"著重於多媒體的設計與製作以及資訊傳媒的企劃與應用"
    },
    {
        id:"2",
        name:"科技組",
        text:"著重於互動資訊科技之應用"
    }
]

export const sponsors=[
    {
        id:"1",
        img:"https://fakeimg.pl/300/",
        name:"test",
    },
    {
        id:"2",
        img:"https://fakeimg.pl/300/",
        name:"test",
    },
    {
        id:"3",
        img:"https://fakeimg.pl/300/",
        name:"test",
    },
    {
        id:"4",
        img:"https://fakeimg.pl/300/",
        name:"test",
    },
    {
        id:"5",
        img:"https://fakeimg.pl/300/",
        name:"test",
    },
    {
        id:"6",
        img:"https://fakeimg.pl/300/",
        name:"test",
    }
    ,
    {
        id:"7",
        img:"https://fakeimg.pl/300/",
        name:"test",
    }
]

export const contacts=[
    {
        id:"1",
        img:"./src/assets/img/ig.png",
        link:"https://www.instagram.com/hung_dodo0427/",
        name:"test",
    },
    {
        id:"2",
        img:"./src/assets/img/fb.png",
        link:"https://www.instagram.com/hung_dodo0427/",
        name:"test",
    },
]

export const C1=[
    {
        id:"1",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"2",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"3",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"4",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"5",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"6",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"7",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"8",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"9",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"10",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"11",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"12",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },{
        id:"13",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"14",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"15",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
]

export const C2=[
    {
        id:"1",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"2",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"3",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"4",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"5",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"6",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"7",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"8",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"9",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"10",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"11",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"12",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },{
        id:"13",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"14",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
    {
        id:"15",
        img:"https://fakeimg.pl/300/",
        name:"test"
    },
]