export const groups = [
  {
    id: "1",
    img: "/img/market.png",
    name: "行銷組",
    text:
      "針對單一主題性的規劃行銷，" +
      "\n" +
      "以視覺設計及行銷概念作為展出內容。",
    route: "/work/market",
  },
  {
    id: "2",
    img: "/img/animation.png",
    name: "影視組",
    text: "由動畫短片及劇情短片" + "\n" + "共同舉辦小型的影展輪播。",
    route: "/intro/film",
  },
  {
    id: "3",
    img: "/img/interact.png",
    name: "互動組",
    text:
      "結合程式設計開發互動裝置，" +
      "\n" +
      "使觀展人親身參與並體驗其中的樂趣。",
    route: "/work/interact",
  },
  {
    id: "4",
    img: "/img/game.png",
    name: "遊戲組",
    text:
      "除了傳統的 PC遊戲外，" +
      "\n" +
      "還會以2D、3D的呈現手法" +
      "\n" +
      "製作多元類型的遊戲。",
    route: "/work/game",
  },
];

export const classes = [
  {
    id: "1",
    name: "設計組",
    group: "c2",
    text: "著重於多媒體的設計與製作以及" + "\n" + "資訊傳媒的企劃與應用",
  },
  {
    id: "2",
    name: "科技組",
    group: "c1",
    text: "著重於互動資訊科技之應用",
  },
];

export const sponsors = [
  {
    id: "1",
    img: "/img/1200px-Emblem_of_Taoyuan_City.svg.png",
    name: "test",
  },
  {
    id: "2",
    img: "/img/2111031134372079761813-2.jpg",
    name: "test",
  },
  {
    id: "3",
    img: "/img/300004163_210694394614458_1982748922942161344_n.jpg",
    name: "test",
  },
  {
    id: "4",
    img: "/img/301115969_385086180471596_520779162512465737_n.jpg",
    name: "test",
  },
  {
    id: "5",
    img: "/img/ROC_Taoyuan_City_Council_logo.svg.png",
    name: "test",
  },
];

export const contacts = [
  {
    id: "1",
    img: "/img/ig.jpg",
    link: "https://www.instagram.com/yzuic_26/",
  },
  {
    id: "2",
    img: "/img/fb.jpg",
    link: "https://www.facebook.com/yzuic26th",
  },
];

export const C1 = [
  {
    id: "1",
    img: "/19/IMG_7929.JPG",
    name: "吳子郇",
    mail: "Ezra40907@gmail.com",
    profile: "無",
    experience: ["宇曜智能股份有限公司-後端實習生", "ISEE校園電視台-器材長"],
    skill: ["Blender", "Unreal", "C++", "Git", "Linux"],
  },
  {
    id: "2",
    img: "/19/IMG_7928.JPG",
    name: "呂晉丞",
    mail: "aaa710140505@gmail.com",
    profile: "https://medium.com/@kenken880929",
    experience: ["元智大學資傳系5402實驗室實習生"],
    skill: ["django", "golang", "Unreal5 Blueprint"],
  },
  {
    id: "3",
    img: "/17/IMG_7938.JPG",
    name: "陳俞蓁",
    mail: "chochenohc@gmail.com",
    profile:
      "https://drive.google.com/file/d/1gZLiVvJbypP367thmcZgc-9VP2VaeYr9/view?usp=drivesdk",
    experience: [
      "格敦企業-遊戲程式設計師實習生",
      "元智大學-有庠廳導播室工讀生",
    ],
    skill: ["Unity", "AR", "網頁前端程式設計"],
  },
  {
    id: "4",
    img: "/5/IMG_7950.JPG",
    name: "張耘嘉",
    mail: "sarahchang0119@gmail.com",
    profile: "無",
    experience: [
      "元智大學英語營助教",
      "資料結構專任助教",
      "德和月網頁設計實習生",
    ],
    skill: ["Figma", "Adobe XD", "PhotoShop"],
  },
  {
    id: "5",
    img: "/15/IMG_7828.JPG",
    name: "余博洋",
    mail: "1qaz987@gmail.com",
    profile:
      "https://drive.google.com/file/d/1ojTiKLvNVfDM3pweFbyUv3p6PYo00x1_/view?usp=sharing",
    experience: ["無"],
    skill: ["unity", "C#", "C++", "C", "Git", "Linux"],
  },
  {
    id: "6",
    img: "/13/IMG_7608.JPG",
    name: "蔡易辰",
    mail: "bobolina0910@gmail.com",
    profile:
      "https://drive.google.com/drive/folders/1adMNWGK-DzpLKo6rZQEAknoOWJLXn_9I?usp=share_link",
    experience: [
      "橘子蘋果常態班-助教",
      "橘子蘋果python遊戲體驗營-學習教練",
      "橘子蘋果課程組-實習生",
    ],
    skill: ["介面設計", "網頁前端"],
  },
  {
    id: "7",
    img: "/12/IMG_7908.JPG",
    name: "許靜玟",
    mail: "chrissyhsu.i@gmail.com",
    profile: "無",
    experience: ["MaiCoin AMIS Labs Frontend Engineer Intern"],
    skill: ["前端網頁程式設計", "Next.jsl"],
  },
  {
    id: "8",
    img: "/12/IMG_7912.JPG",
    name: "莊文惠",
    mail: "vina900407@gmail.com",
    profile: "https://vina900407.wixsite.com/website",
    experience: ["宇宙製造股份有限公司-行銷助理(實習生)", "Polakids粉專小編"],
    skill: ["文案編寫", "顧客關係管理"],
  },
  {
    id: "9",
    img: "/12/IMG_7911.JPG",
    name: "鄭淳云",
    mail: "b891023502@gmail.com",
    profile: "https://b891023502.wixsite.com/ccyportfolio",
    experience: ["方塊磚智慧顯示公司-PM實習生", "高雄捷運智慧服務台專案管理"],
    skill: ["專案管理"],
  },
  {
    id: "10",
    img: "/13/IMG_7610.JPG",
    name: "張舒涵",
    mail: "chang910407@gmail.com",
    profile:
      "https://drive.google.com/drive/folders/1uhzIqCBxoKtOcSKid2gl923AyfXi5dkQ?usp=share_link",
    experience: ["高雄市立圖書館-實習生"],
    skill: ["網頁程式設計"],
  },
  {
    id: "11",
    img: "/16/IMG_7997.JPG",
    name: "詹采融",
    mail: "maffy0426@gmail.com",
    profile:
      "https://issuu.com/oooo_rong/docs/_e4_bd_9c_e5_93_81_e9_9b_86?fbclid=IwAR10Q2mNn7gpvHVjtp4dyyAJD1nMVk9195PLwyw7HxlZlHKp3YMZG8WRQKk",
    experience: ["VS Media社群影片剪輯實習生", "畢籌會公關"],
    skill: ["行銷企劃", "Premiere", "PhotosShop"],
  },
  {
    id: "12",
    img: "/5/IMG_7953.JPG",
    name: "謝昕倢",
    mail: "selina900125@gmail.com",
    profile: "無",
    experience: ["趣放娛樂影片剪輯實習生"],
    skill: ["Adobe Premiere", "Adobe After Effect", "figma"],
  },
  {
    id: "13",
    img: "/6/IMG_7706.JPG",
    name: "鄭兆晉",
    mail: "mogaco666@gmail.com",
    profile: "無",
    experience: [
      "VR/AR教育應用創造競賽[其他組] 優等獎",
      "VR/AR教育應用創造競賽[教學應用組] 佳作獎",
      "109五育學業銀質獎",
    ],
    skill: ["python自動化程式", "excel建檔管理", "人資管理", "unity"],
  },
  {
    id: "14",
    img: "/13/IMG_7614.JPG",
    name: "江若仙",
    mail: "qquuie0424@gmail.com",
    profile:
      "https://drive.google.com/drive/folders/1KKP_IcVhnrtTXrpTbJqclvog5lJH3bM6?usp=share_link",
    experience: ["發亮科技-實習生"],
    skill: ["unity專案設計"],
  },
  {
    id: "15",
    img: "/12/IMG_7907.JPG",
    name: "黃郁淇",
    mail: "joyce890926@gmail.com",
    profile:
      "https://drive.google.com/file/d/1CTH3sfCk8f2mS891LoIcXy_olX3hJtkA/view",
    experience: ["富邦人壽前端工程師實習生"],
    skill: ["前端網頁程式設計", "Vue.js", "Tailwind.css"],
  },
  {
    id: "16",
    img: "/5/IMG_7951.JPG",
    name: "林劭謙",
    mail: "boy19790710@gmail.com",
    profile: "無",
    experience: [
      "UniQlo 60秒可以折7件衣服",
      "麵店洗碗pro級",
      "SEITO DEPT",
      "行銷實習生",
    ],
    skill: ["InDesign", "premiere", "Figma", "Notion", "LightRoom"],
  },
  {
    id: "17",
    img: "/15/IMG_7826.JPG",
    name: "王　晨",
    mail: "mark02160216@gmail.com",
    profile:
      "https://drive.google.com/drive/folders/1eeE56uiKRyzbQxqgI6d7J__PPb74-8s7?usp=share_link",
    experience: ["無"],
    skill: ["Unity", "C#", "遊戲企劃"],
  },
  {
    id: "18",
    img: "/4/IMG_7919.JPG",
    name: "李家儀",
    mail: "ja971212@gmail.com",
    profile:
      "https://drive.google.com/file/d/1EbXw3l1hOfJOHHyykjwTU72V7doUwwmg/view",
    experience: [
      "資傳系系學會執行秘書",
      "元智大學資傳系 林佩瑜助理教授研究助理",
    ],
    skill: ["文案撰寫", "資料統整"],
  },
  {
    id: "19",
    img: "/8/IMG_7670.JPG",
    name: "蔡容安",
    mail: "yhjhs92929.2016@gmail.com",
    profile: "無",
    experience: [
      "元智大學資訊傳播學系ISEE校內實習",
      "元智大學人文社會學院 虛擬攝影棚手冊編輯",
      "社團法人台灣農業科技資源運籌管理學會 行銷計畫推廣助理",
    ],
    skill: ["前端網頁程式設計", "平面設計", "Unity"],
  },
  {
    id: "20",
    img: "/2/IMG_7404.JPG",
    name: "溫存正",
    mail: "hanklovemrs30@gmail.com",
    profile: "無",
    experience: ["漢鼎科技股份有限公司-實習生"],
    skill: ["網頁程式開發"],
  },
  {
    id: "21",
    img: "/10/IMG_8490.JPG",
    name: "魏承恩",
    mail: "sam90315@gmail.com",
    profile: "無",
    experience: ["國賓影城計時人員", "康思迅數位行銷公司-網頁實習生"],
    skill: ["前端網頁開發", "Vue.js"],
  },
  {
    id: "22",
    img: "/16/IMG_7996.JPG",
    name: "陳栗芩",
    mail: "bolly422466@gmail.com",
    profile: "https://issuu.com/clc2777/docs/",
    experience: ["ISEE TV 企劃組", "尼克影像工作室-錄影師"],
    skill: ["Maya建模", "企劃發想", "攝影"],
  },
  {
    id: "23",
    img: "/2/IMG_7403.JPG",
    name: "涂紜瑄",
    mail: "tuuuyhsuan@gmail.com",
    profile: "無",
    experience: ["威科技股份有限公司-前端實習生"],
    skill: ["前端網頁設計"],
  },
  {
    id: "24",
    img: "/8/IMG_7669.JPG",
    name: "陳堂宇",
    mail: "sam.sam.chen123@gmail.com",
    profile: "https://reurl.cc/EG779R",
    experience: ["元智大學資傳系 鄧進宏教授 AR研究計畫實習"],
    skill: ["AR", "影片剪輯"],
  },
  {
    id: "25",
    img: "/18/IMG_7592.JPG",
    name: "洪立恒",
    mail: "hungwork510031@gmail.com",
    profile: "https://reurl.cc/jldpOZ",
    experience: ["無"],
    skill: ["全端網頁程式設計", "React.js", "Express.js"],
  },
  {
    id: "26",
    img: "/7/IMG_8371.JPG",
    name: "蔡坤霖",
    mail: "deathknight285@gmail.com",
    profile: "https://deathknight285.wixsite.com/my-site",
    experience: [
      "麥威科技公司-後端網頁實習生",
      "創客盃 智慧資訊組 優等",
      "元智大學義工獎",
    ],
    skill: ["dotnet後端網頁程式設計", "python爬蟲"],
  },
  {
    id: "27",
    img: "/18/IMG_7591.JPG",
    name: "方子樽",
    mail: "jmjmjim1101@gmail.com",
    profile: "https://github.com/ZJimFang",
    experience: ["NASA app 全球40名,宇宙製造網頁全端實習生","元智明星賽三分球亞軍"],
    skill: ["網頁程式設計", "三分射手"],
  },
  {
    id: "28",
    img: "/6/IMG_7708.JPG",
    name: "宋柏勳",
    mail: "b2001900814@gmail.com",
    profile: "無",
    experience: ["國立科學工藝博物館-實習生"],
    skill: ["影片剪輯", "3D建模"],
  },
  {
    id: "29",
    img: "/18/IMG_7589.JPG",
    name: "陳柏諺",
    mail: ":z7246590@gmail.com",
    profile: "https://github.com/mm7246591",
    experience: ["捷德運動股份公司-前端工程師", "網頁程式設計助教"],
    skill: ["Vue.js"],
  },
  {
    id: "30",
    img: "/14/IMG_8504.JPG",
    name: "簡文勝",
    mail: "fpswesan@gmail.com",
    profile:
      "https://drive.google.com/file/d/1WiziZtPwS-xNvqRtl5o5fXcWhdXtdF2h/view?usp=drivesdk",
    experience: [
      "元智大學資傳系 實習團隊 ISEE -企劃組長",
      "元智大學資傳系 張世明副教授之助理",
      "Intake Education -影音實習生",
    ],
    skill: ["動態攝影"],
  },
  {
    id: "31",
    img: "/11/IMG_7598.JPG",
    name: "郭岱旻",
    mail: "daiming1108@gmail.com",
    profile: "無",
    experience: [
      "迪威運動股份有限公司-群行銷暑期實習生",
      "《欲無⽌盡-象棋篇》劇情短⽚ 第五屆桃園廉政電影節 大專青年組佳作 ｜收音",
      "《SDGS-飢餓與貧窮》概念短片｜燈光指導",
    ],
    skill: ["社群行銷"],
  },
  {
    id: "32",
    img: "/8/IMG_7671.JPG",
    name: "李汶儒",
    mail: "maylee900116@gmail.com",
    profile: "無",
    experience: [
      "茂綸股份有限公司 資訊部門工讀生",
      "倍思親國際有限公司 美編實習生",
    ],
    skill: ["PhotoShop", "Arduino", "基礎前端網頁程式設計"],
  },
  {
    id: "33",
    img: "/4/IMG_7921.JPG",
    name: "張亞芸",
    mail: "407boo@gmail.com",
    profile:
      "https://drive.google.com/file/d/125rAw1tbilUSAJrGKFsSdhtDZlfOfs7D/view ",
    experience: ["元智大學資傳系 鄧進宏副教授助理"],
    skill: ["Unity", "PhotoShop"],
  },
  {
    id: "34",
    img: "/15/IMG_7830.JPG",
    name: "陳修業",
    mail: "kevin.bobo2001@gmail.com",
    profile:
      "https://drive.google.com/file/d/1x25DN55-_Oavi4ww87OY5rl0FXuhz3qs/view?usp=sharing",
    experience: ["無"],
    skill: ["3D建模"],
  },
  {
    id: "35",
    img: "/6/IMG_7704.JPG",
    name: "張鈺玟",
    mail: "a0933768506@gmail.com",
    profile: "無",
    experience: ["無極限 行銷企劃助理", "彭園三重館 婚禮場控"],
    skill: ["文案撰寫", "創意發想"],
  },
  {
    id: "36",
    img: "/6/IMG_7709.JPG",
    name: "李宜庭",
    mail: "teresa900816@gmail.com",
    profile: "無",
    experience: ["昇恆昌 新媒體事業部設計組實習生"],
    skill: ["行銷企劃", "室內設計", "AutoCad"],
  },
  {
    id: "37",
    img: "/9/IMG_8418.JPG",
    name: "汪承緒",
    mail: "sh15871114@gmail.com",
    profile: "無",
    experience: ["無"],
    skill: ["前端網站設計"],
  },
  {
    id: "38",
    img: "/6/IMG_7707.JPG",
    name: "蘇于翔",
    mail: "suyuhsiang891013@gmail.com",
    profile: "無",
    experience: [
      "VR/AR教育應用創造競賽[其他組] 優等獎",
      "VR/AR教育應用創造競賽[教學應用組] 佳作獎",
    ],
    skill: ["3D建模"],
  },
  {
    id: "39",
    img: "/14/IMG_8500.JPG",
    name: "邱翊柏",
    mail: "bertcso1104@gmail.com",
    profile:
      "https://bertcso1104.wixsite.com/my-site?fbclid=PAAaaZ0Xx_3h0jJkHgGtB-4BKAeCi75YH1WoTy-BJxyIEdntPVnLQE6k8MDJ0",
    experience: ["gj94 film studio 實習生"],
    skill: ["平面攝影", "動態攝影"],
  },
  {
    id: "40",
    img: "/1/IMG_8392.JPG",
    name: "郭心柔",
    mail: "h4207289@gmail.com",
    profile:
      "https://drive.google.com/drive/folders/1mtXh3tR4rRUk7fh5RQgyXscXRHNx-0EU",
    experience: ["無"],
    skill: ["手機應用程式開發", "動畫後製"],
  },
  {
    id: "41",
    img: "/10/IMG_8484.JPG",
    name: "呂柏龍",
    mail: "peterlu900203@gmail.com",
    profile:
      "https://mitrofan2001.github.io/?fbclid=PAAaYbZ45roXo01-sLre_rLDVICiNUX5zuW-XDNFISQr_1ajMkZJZ8EWmMAoU",
    experience: [
      "元智男排代表隊",
      "富邦人壽 前端實習生",
      "元智資傳科技組 副班代",
    ],
    skill: ["Figma", "前端網頁開發", "React.js", "Vue.js", "Unity Vuforia"],
  },
  {
    id: "42",
    img: "/5/IMG_7954.JPG",
    name: "徐振瑄",
    mail: "a0926020372@gmail.com",
    profile: "無",
    experience: ["元智大學方文聘教授實習生", "嵐奕科技公司實習生"],
    skill: ["Python", "Django", "JavaScript", "Netflix", "Spotify"],
  },
  {
    id: "43",
    img: "/16/IMG_7999.JPG",
    name: "郭璦菁",
    mail: "royee13028@gmail.com",
    profile: "https://reurl.cc/d7rKa6",
    experience: ["宇宙製造社群實習生", "Polakids網站UI設計"],
    skill: ["前端網頁程式設計", "Unity"],
  },
  {
    id: "44",
    img: "/20/IMG_8401.JPG",
    name: "許其彬",
    mail: " jeff808328@gmail.com",
    profile: "https://github.com/jeff808328",
    experience: ["格敦企業 遊戲美術實習生"],
    skill: ["C#", "C++程式設計", "Unity與插件使用", "專案版本管理"],
  },
  {
    id: "45",
    img: "/9/IMG_8419.JPG",
    name: "杜孟洋",
    mail: "daniel509401@gmail.com",
    profile:
      "https://drive.google.com/file/d/1Gi8OC_LeWE_sJ0V3CANMMvDz_UbrLZsr/view?usp=share_link",
    experience: ["無"],
    skill: ["前端網站設計", "Arduino"],
  },
  {
    id: "46",
    img: "/7/IMG_8370.JPG",
    name: "李　曜",
    mail: "leoleekiom@gmail.com",
    profile: "https://reurl.cc/lvLq3A",
    experience: [
      "研究計畫專業實習-VR/AR教學計畫",
      "創客盃 智慧資訊組 優等",
      "VR/AR教育競賽 入圍",
    ],
    skill: ["Unity", "C#", "node.js"],
  },
  {
    id: "47",
    img: "/13/IMG_7613.JPG",
    name: "裴氏瓊如",
    mail: "candybui61@gmail.com",
    profile:
      "https://drive.google.com/drive/folders/17r_Oh0BqwRWlF4xVPqyKEXErlxiX2x6V?usp=share_link",
    experience: ["名留集團-實習生", "五倍紅寶石軟體開發-實習生"],
    skill: ["React.js", "Ruby on rails", "Unity專案設計"],
  },
  {
    id: "48",
    img: "/8/IMG_7667.JPG",
    name: "劉文業",
    mail: "havekiez01@gmail.com",
    profile: "無",
    experience: ["無"],
    skill: ["C++", "HTML", "JavaScript"],
  },
  {
    id: "49",
    img: "/17/IMG_7940.JPG",
    name: "王維亭",
    mail: "weitingmm@gmail.com",
    profile:
      "https://drive.google.com/file/d/1SBuGAnsEeqvW4JPbVZaHwOEeboPerAf5/view?usp=drivesdk",
    experience: ["創客競賽智慧資訊組 佳作", "五倍紅寶石 網頁全端實習生"],
    skill: ["全端網頁程式設計", "Ruby on Rails", "Unity遊戲設計"],
  },
  {
    id: "50",
    img: "/14/IMG_8503.JPG",
    name: "陳柏旭",
    mail: "mark249028@gmail.com",
    profile: "無",
    experience: ["洄游創生實習生"],
    skill: ["平面攝影"],
  },
  {
    id: "51",
    img: "/22/IMG_8492.JPG",
    name: "雷子誼",
    mail: "angelina.093890@gmail.com",
    profile: "無",
    experience: ["無"],
    skill: ["平面設計", "AI", "PS"],
  },
  {
    id: "52",
    img: "/21/IMG_8380.JPG",
    name: "孫睦桓",
    mail: "milessun0507@gmail.com",
    profile: "https://sites.google.com/view/milesportfolio/home",
    experience: [
      "Intel 校園社群大使",
      "MSI 微星科技校園大使",
      "裕隆日產校園大使",
    ],
    skill: ["Wordpress架站", "企劃", "Google Analytics"],
  },
];

export const C2 = [
  {
    id: "1",
    img: "/10/IMG_8486.JPG",
    name: "陳慧心",
    mail: "catpaw0218@gmail.com",
    profile:
      "https://drive.google.com/file/d/1LZ1ZqclRUJODsKf9TbWfekk_mKsSfLnT/view?usp=drivesdk",
    experience: ["瑿美人行銷美工", "系排隊長"],
    skill: ["平面設計", "illustrator"],
  },
  {
    id: "2",
    img: "/2/IMG_7406.JPG",
    name: "蒲芳榆",
    mail: "puangela02@gmail.com",
    profile: "無",
    experience: ["金犢獎平面設計-入圍", "格敦企業股份有限公司-設計部實習生"],
    skill: ["平面設計"],
  },
  {
    id: "3",
    img: "/3/IMG_7807.JPG",
    name: "王鈞杭",
    mail: "world90829@gmail.com",
    profile: "無",
    experience: ["Amazing talker-影音實習生"],
    skill: ["影片製作剪輯", "攝影"],
  },
  {
    id: "4",
    img: "/10/IMG_8485.JPG",
    name: "陳怡安",
    mail: "Judychen864@yahoo.com.tw",
    profile: "無",
    experience: ["宇宙製造有限公司實習生"],
    skill: ["2D電腦繪圖", "角色設計", "平面設計"],
  },
  {
    id: "5",
    img: "/13/IMG_7609.JPG",
    name: "白紀葳",
    mail: "dona1599877@gmail.com",
    profile:
      "https://drive.google.com/file/d/1NDbK3_ctff4ZA1llQGR3YWQBQ_AeJ_R_/view?usp=share_link",
    experience: [
      "Vtuber黑客松創作大賽[台灣原創IP跨域組-最佳影片獎]",
      "金犢獎平面廣告設計-入圍",
    ],
    skill: ["電腦繪圖"],
  },
  {
    id: "6",
    img: "/1/IMG_8388.JPG",
    name: "范皓凌",
    mail: "bonnie20001107@gmail.com",
    profile:
      "https://drive.google.com/drive/folders/1-5Xm6Sbva_4blSa7ztCbOEG2i_4zzeUO",
    experience: ["姿嘉麗植萃有限公司實習-設計美編"],
    skill: ["插圖", "美術設計", "PhotoShop", "Illustrator"],
  },
  {
    id: "7",
    img: "/11/IMG_7601.JPG",
    name: "許雨雯",
    mail: "yuwenhsu0515@gmail.com",
    profile:
      "https://drive.google.com/file/d/1mSr_YhYW3mmgJxCJ5_Pp9EBx9c-Bdu5Y/view?usp=drivesdk",
    experience: [
      "《欲無⽌盡-象棋篇》劇情短⽚ 桃園廉政電影節佳作－導演｜攝影｜剪輯｜調色",
      "Bolly 阮⽲茜《不完美⼥孩》Music Video－製⽚",
      "《遺失的聚落：⽯⾨⽔庫移民故事》紀錄⽚－動態錄影｜剪輯",
    ],
    skill: ["影像製作", "⼈像攝影", "商品攝影", "專案管理"],
  },
  {
    id: "8",
    img: "/18/IMG_7593.JPG",
    name: "謝昀軒",
    mail: "yunxuan9025@gmail.com",
    profile: "https://www.behance.net/juliahsieh",
    experience: ["無"],
    skill: ["繪圖", "UIUX設計", "平面設計", "動態設計"],
  },
  {
    id: "9",
    img: "/16/IMG_7995.JPG",
    name: "李建暐",
    mail: "steven10022000@gmail.com",
    profile: "https://issuu.com/weybabe/docs/_",
    experience: ["泰式料理社群小編&美編設計", "藝術塗裝實習生"],
    skill: ["平面設計", "藝術創作", "刷油漆"],
  },
  {
    id: "10",
    img: "/3/IMG_7806.JPG",
    name: "劉俊廷",
    mail: "steambread2001@gmail.com",
    profile: "無",
    experience: [
      "時報金犢獎 - 掌閱精選APP品牌形象廣告設計獎-平面類 入圍",
      "唯晶科技-2D美術實習生",
    ],
    skill: ["日式人物插畫"],
  },
  {
    id: "11",
    img: "/2/IMG_7401.JPG",
    name: "周貝貝",
    mail: "zxcasdf50421@gmail.com",
    profile: "https://zxcasdf50421.wixsite.com/my-site",
    experience: ["水越設計-實習生"],
    skill: ["平面設計", "社群經營", "企劃發想"],
  },
  {
    id: "12",
    img: "/14/IMG_8502.JPG",
    name: "黃昱軒",
    mail: "polk3395@gmail.com",
    profile: "無",
    experience: ["五座森林影像-實習生", "金魚數位音樂-實習生"],
    skill: ["動態影像拍攝"],
  },
  {
    id: "13",
    img: "/12/IMG_7910.JPG",
    name: "陳郁臻",
    mail: "j90227555@gmail.com",
    profile: "https://issuu.com/chenyuchendesign/docs/portfolio",
    experience: ["無介整合設計制作所-實習生"],
    skill: ["使用者介面設計", "使用者經驗設計"],
  },
  {
    id: "14",
    img: "/17/IMG_7939.JPG",
    name: "蘇煒筑",
    mail: "sue90529@gmail.com",
    profile: "https://judysu66.wixsite.com/my-site-4",
    experience: [
      "LONDON INTERNATIONAL CREATIVE COMPETITION - Finalists in Illustrate (graphic)",
      "英國倫敦國際創意大賽-平面設計與插畫類 決賽入圍獎",
      "International Design Awards - Graphic Design work 入圍 IDA",
      "BORING Design Lab 品牌識別設計實習生",
    ],
    skill: ["視覺插畫", "品牌識別設計", "美術", "平面設計"],
  },
  {
    id: "15",
    img: "/11/IMG_7597.JPG",
    name: "曾佳容",
    mail: "qsdfg7350456@gmail.com",
    profile:
      "https://drive.google.com/file/d/1niI1iRBzjwcGqxCwNVIoNyLqs1uHrpgu/view?usp=share_link",
    experience: [
      "京極映畫影像公司-動畫特效師",
      "展亦影業-後期特效師",
      "影視學院-AE講師",
    ],
    skill: ["2D動畫特效", "3D動畫", "調光調色", "攝影剪輯"],
  },
  {
    id: "16",
    img: "/17/IMG_7941.JPG",
    name: "邱靖文",
    mail: "carrie159357@gmail.com",
    profile: "https://reurl.cc/V8aANZ",
    experience: [
      "LONDON INTERNATIONAL CREATIVE COMPETITION - Finalists in Illustrate (graphic)",
      "英國倫敦國際創意大賽-平面設計與插畫類 決賽入圍獎",
      "旺旺集團廣告設計獎－產品類－平面類 入圍獎",
      "捷德運動股份有限公司 實習生",
    ],
    skill: ["平面設計", "UI設計", "插圖設計"],
  },
  {
    id: "17",
    img: "/15/IMG_7829.JPG",
    name: "陳忻妤",
    mail: "reita1859201@gmail.com",
    profile:
      "https://drive.google.com/file/d/1wOfACVH6yeH8cF4wtRizylaHTTNNaS7h/view?usp=drivesdk",
    experience: ["無"],
    skill: ["2D美術"],
  },
  {
    id: "18",
    img: "/7/IMG_7816.JPG",
    name: "施佩妤",
    mail: "racy91689@gmail.com",
    profile: "https://racy91689.wixsite.com/my-site",
    experience: ["栯菘創意傳播-設計實習生", "創客盃 智慧資訊組 優等"],
    skill: ["海報設計", "包裝設計", "編排設計", "插圖設計", "2D動畫設計"],
  },
  {
    id: "19",
    img: "/6/IMG_7705.JPG",
    name: "葉沛宣",
    mail: "無",
    profile: "無",
    experience: ["安達窯陶瓷藝術股份公司-手作人員實習生"],
    skill: ["電腦繪圖", "手繪", "平面設計"],
  },
  {
    id: "20",
    img: "/7/IMG_8368.JPG",
    name: "薛　涵",
    mail: "hannah891007@gmail.com",
    profile: "https://hannah0794.wixsite.com/my-site",
    experience: [
      "時報金犢獎-優勝獎",
      "創客盃 智慧資訊組 優等",
      "IKEA 視覺陳列設計實習生",
    ],
    skill: ["海報設計", "包裝設計", "編排設計", "插圖設計", "LOGO設計"],
  },
  {
    id: "21",
    img: "/1/IMG_8391.JPG",
    name: "彭欣慧",
    mail: "cathy172425@gmail.com",
    profile: "https://issuu.com/cathy_portfolio/docs/portfolio",
    experience: [
      "宇宙製造公司實習",
      "參加2020遊戲新星點亮計畫",
      "資傳之夜（美宣組）",
    ],
    skill: ["平面設計", "2D電繪", "角色設計"],
  },
  {
    id: "22",
    img: "/12/IMG_7909.JPG",
    name: "羅珮瑄",
    mail: "a0970203382@gmail.com",
    profile: "https://a0970203382.wixsite.com/my-site-2",
    experience: ["雞設士工作室實習生", "Uber Eat、Acer等廣告拍攝參與"],
    skill: ["平面設計"],
  },
  {
    id: "23",
    img: "/16/IMG_7998.JPG",
    name: "蔡昀芬",
    mail: "20001027sharontsai@gmail.com",
    profile: "無",
    experience: [
      "格敦企業設計助理美編實習生",
      "畢籌會活動",
      "金犢獎豆力脆平面設計類入圍最佳美術設計",
    ],
    skill: ["平面設計", "Procreate", "figma", "手繪"],
  },
  {
    id: "24",
    img: "/20/相片 2022-12-31 08.14.04 下午.jpg",
    name: "張文安",
    mail: "angus14242@gmail.com",
    profile: "無",
    experience: ["無"],
    skill: ["電腦繪圖", "3D建模/動畫", "unity遊戲程式", "遊戲特效", "Linux"],
  },
  {
    id: "25",
    img: "/13/IMG_7611.JPG",
    name: "彭奕綾",
    mail: "66pauline@gmail.com",
    profile:
      "https://drive.google.com/drive/folders/1xOe27MjGW5esOlonbFAJ9N0WUk4B3RJq?usp=share_link",
    experience: [
      "Vtuber黑客松創作大賽[台灣原創IP跨域組-最佳影片獎]",
      "金犢獎平面廣告設計-入圍",
    ],
    skill: ["視覺介面設計", "電腦繪圖"],
  },
  {
    id: "26",
    img: "/14/IMG_8501.JPG",
    name: "王怡潔",
    mail: "gigiw129@gmail.com",
    profile: "https://gigiw129.wixsite.com/wyc-portfolio",
    experience: ["IKEA實習生", "Travatar UIUX 助理", "NRVS粉專美編"],
    skill: ["UI/UX設計", "平面設計", "繪圖"],
  },
  {
    id: "27",
    img: "/9/IMG_8421.JPG",
    name: "游又潔",
    mail: "yoyoyu6888@gmail.com",
    profile:
      "https://drive.google.com/file/d/1oKyjq5gnq5jMSmbxkoZ6XiB9gissClzo/view?usp=drivesdk",
    experience: ["元智大學資傳系排球隊副隊長"],
    skill: ["手繪插畫", "電繪", "繪畫設計"],
  },
  {
    id: "28",
    img: "/1/IMG_8394.JPG",
    name: "陳逸欣",
    mail: "23445122a@gmail.com",
    profile:
      "https://drive.google.com/folderview?id=1hvulL7ZtKGyJbASzR2NTddUu7hpbeUFq",
    experience: ["如牧創新-社群實習生"],
    skill: ["平面設計", "插畫"],
  },
  {
    id: "29",
    img: "/7/IMG_8367.JPG",
    name: "潘雅歆",
    mail: "yaxin.plan@gmail.com",
    profile: " https://yaxin-portfolio.webflow.io/",
    experience: [
      "tenten - D2C電商品牌/ 新創孵化器 影音實習生",
      "創客盃 智慧資訊組 優等",
    ],
    skill: ["UI介面設計", "影像設計", "平面設計"],
  },
  {
    id: "30",
    img: "/9/IMG_8422.JPG",
    name: "吳采芊",
    mail: "ninawoot510mh@gmail.com",
    profile: "無",
    experience: ["無"],
    skill: ["平面設計", "多媒體影像處理", "影片剪輯"],
  },
  {
    id: "31",
    img: "/10/IMG_8487.JPG",
    name: "陳主祥",
    mail: "seanchen110300@gmail.com",
    profile: "無",
    experience: [
      "上海儲蓄銀行資訊研發處短期實習生",
      "廣影科技露營行銷部門企劃",
      "你的好蜂蜜產品代理人",
    ],
    skill: ["系統分析", "資訊系統管理", "專案管理", "python程式設計"],
  },
  {
    id: "32",
    img: "/7/IMG_8369.JPG",
    name: "陳　涓",
    mail: "nicole0501chen@gmail.com",
    profile: "https://nicole0501chen.wixsite.com/my-site",
    experience: ["IKEA公司 視覺陳列設計實習生", "創客盃 智慧資訊組 優等"],
    skill: ["平面設計", "展示設計", "包裝設計", "編排設計"],
  },
  {
    id: "33",
    img: "/17/IMG_7942.JPG",
    name: "周方浩",
    mail: "mike111chou@gmail.com",
    profile: "shorturl.at/axFJ6",
    experience: ["遠傳電信-實習生", "金犢獎平面類 銅犢奬 第二名"],
    skill: ["影視剪輯", "音樂音效", "平面/動態設計"],
  },
  {
    id: "34",
    img: "/4/IMG_7924.JPG",
    name: "洪幸宇",
    mail: "uijkmuijk@gmail.com",
    profile:
      "https://drive.google.com/file/d/1k-Mh8W9FZuddIRiB_aJ-xea_Xg5r8SRU/view",
    experience: ["無"],
    skill: ["3D建模"],
  },
  {
    id: "35",
    img: "/8/IMG_7668.JPG",
    name: "蔡尚恩",
    mail: "saenwoody@gmail.com",
    profile: "https://reurl.cc/mln97M",
    experience: [
      "入圍金犢獎廣告平面設計獎",
      "參與元智大學資訊傳播學系ISEE校內實習",
      "擔任元智光鹽唱詩社-美宣",
    ],
    skill: ["影像合成", "平面設計", "影片剪輯"],
  },
  {
    id: "36",
    img: "/4/IMG_7923.JPG",
    name: "宋翊彰",
    mail: "a29302587@gmail.com",
    profile:
      "https://drive.google.com/file/d/1SpiqqT2ZRPkdjgvodyjTMHjUIth9VJpO/view",
    experience: ["擔任資傳系系學會會長"],
    skill: ["Arduino程式", "展場架設"],
  },
  {
    id: "37",
    img: "/9/IMG_8420.JPG",
    name: "都芊如",
    mail: "halove880915@gmail.com",
    profile: "無",
    experience: ["韓國中央大學交換生"],
    skill: ["平面設計", "影片編輯", "美編管理"],
  },
  {
    id: "38",
    img: "/2/IMG_7405.JPG",
    name: "吳冠緯",
    mail: "g0972968086@gmail.com",
    profile: "無",
    experience: ["宅神數位股份有限公司-實習生"],
    skill: ["平面設計"],
  },
  {
    id: "39",
    img: "/4/IMG_7922.JPG",
    name: "廖子硯",
    mail: "boss71888@gmail.com",
    profile:
      "https://drive.google.com/file/d/1voOreEJNgX3NR6BwcYTLZgKuyXB-maye/view",
    experience: ["無"],
    skill: ["修圖後製"],
  },
  {
    id: "40",
    img: "/4/IMG_7920.JPG",
    name: "洪佳妤",
    mail: "catmail900403@gmail.com",
    profile:
      "https://drive.google.com/file/d/1VglhCTPRHr2s9cgZ6wL_R1pGnFVDi-md/view",
    experience: ["無"],
    skill: ["動畫", "人物設計"],
  },
  {
    id: "41",
    img: "/20/IMG_8403.JPG",
    name: "洪順祥",
    mail: "aa900424718@gmail.com",
    profile: "無",
    experience: ["『虛擬人黑客松創作大賽 』 IP組_最佳影片"],
    skill: ["電腦繪圖", "前端網頁程式設計", "Unity遊戲程式"],
  },
  {
    id: "42",
    img: "/18/IMG_7590.JPG",
    name: "吳宜樺",
    mail: "rebecca90052626@gmail.com",
    profile: "https://www.behance.net/yihuawu2",
    experience: ["新眺創意實驗室-實習生","《欲無⽌盡-象棋篇》劇情短⽚ 桃園廉政電影節佳作 - 製片","金犢獎平面設計-入圍"],
    skill: ["UI&UX設計", "平面設計", "動態設計"],
  },
  {
    id: "43",
    img: "/20/IMG_8402.JPG",
    name: "鄭　暘",
    mail: "ttiimmoo2020@gmail.com",
    profile: "無",
    experience: [
      "第22屆全國大專校院資訊應用服務創新競賽教育部開放資料創新應用組-第二名",
      "第23屆全國大專校院資訊應用服務創新競賽教育部開放資料創新應用組-佳作",
    ],
    skill: [
      "電腦繪圖",
      "3D建模",
      "遊戲特效",
      "Unity遊戲程式",
      "錄音",
      "音響系統控制",
    ],
  },
  {
    id: "44",
    img: "/16/IMG_7994.JPG",
    name: "張佳明",
    mail: "max121489@gmail.com",
    profile: "https://reurl.cc/d705YD",
    experience: ["宅神企業網頁實習生", "麥田早餐店美編設計"],
    skill: ["Maya建模", "前端網頁設計", "平面設計"],
  },
  {
    id: "45",
    img: "/2/IMG_7402.JPG",
    name: "任力加",
    mail: "jxx19990917@gmail.com",
    profile: "無",
    experience: ["金犢獎平面設計-入圍", "IKEA 設計部門-實習生"],
    skill: ["平面設計"],
  },
  {
    id: "46",
    img: "/3/IMG_7804.JPG",
    name: "莊祥穎",
    mail: "andy6662233@gmail.com",
    profile: "無",
    experience: [
      "時報金犢獎-一般廣告設計類-入圍",
      "首阜企業管理 數位媒體實習生",
    ],
    skill: ["MG動畫", "影片剪輯"],
  },
  {
    id: "47",
    img: "/5/IMG_7952.JPG",
    name: "何若齊",
    mail: "zoeho725@gmail.com",
    profile: "無",
    experience: [
      "水越設計實習生",
      "臺灣文化博覽會—寶島冰菓室參展、第三十屆一般廣告設計項",
      "最佳美術設計項平面類—入圍",
    ],
    skill: ["Adobe Illustrator", "Procreate", "InDesign", "Figma"],
  },
  {
    id: "48",
    img: "/3/IMG_7808.JPG",
    name: "劉智傑",
    mail: "jeffliu890608@gmail.com",
    profile: "無",
    experience: [
      "時報金犢獎-一般廣告設計類-入圍",
      "虚擬人黑客松創作大賽-學生組-第一名",
      "HahaTai 哈哈台-實習生",
    ],
    skill: ["影片製作剪輯", "攝影"],
  },
  {
    id: "49",
    img: "/3/IMG_7805.JPG",
    name: "李為璘",
    mail: "cool23253187@gmail.com",
    profile: "無",
    experience: [
      "時報金犢獎-一般廣告設計類-入圍",
      "虚擬人黑客松創作大賽-原創IP組-第一名",
      "1st price of 2022 NASA International Space App Chellenge of Taoyuan City in Taiwan",
    ],
    skill: ["3D場景建置"],
  },
  {
    id: "50",
    img: "/11/IMG_7594.JPG",
    name: "郭俊語",
    mail: "fish28573268@gmail.com",
    profile: "無",
    experience: ["2021 金犢獎 形象廣告設計獎入圍"],
    skill: ["視覺設計", "UIUX", "PhotoShop", "AI"],
  },
  {
    id: "51",
    img: "/15/IMG_7827.JPG",
    name: "朱王韜",
    mail: "無",
    profile: "無",
    experience: ["無"],
    skill: ["遊戲企劃", "3D建模"],
  },
  {
    id: "52",
    img: "/17/IMG_7943.JPG",
    name: "鄭雨桐",
    mail: "firmianaz7@gmail.com",
    profile: "https://firmianaz7.wixsite.com/website",
    experience: [
      "天采影視-燈光助理",
      "博乐勘探设计Ltd. 景觀設計助理",
      "LONDON INTERNATIONAL CREATIVE COMPETITION - Finalists in Illustrate (graphic)",
      "英國倫敦國際創意大賽-平面設計與插畫類 決賽入圍獎",
    ],
    skill: ["平面設計", "品牌设计", "版面设计"],
  },
  {
    id: "53",
    img: "/11/IMG_7599.JPG",
    name: "陳怡如",
    mail: "cyes30625@gmail.com",
    profile: "https://cyes30625.wixsite.com/ijuhome",
    experience: [
      "桃園忠貞《藝FUN美食》動畫 美術｜收音｜後制｜剪輯",
      "《南投特產》地方介紹短片 動畫補幀｜動捕錄製",
      "《SDGS-飢餓與貧窮》概念短片｜美術指導",
    ],
    skill: ["美術繪畫", "平面設計"],
  },
  {
    id: "54",
    img: "/11/IMG_7596.JPG",
    name: "方湘楀",
    mail: "he02725509@gmail.com",
    profile: "https://he02725509.wixsite.com/bonk",
    experience: [
      "金犢獎-形象廣告設計獎、最佳文案設計-入圍",
      "ISEE影視製作團隊-實習生",
      "在地文化創作徵獎 影片組-第二名",
      "黑客松許擬人創作大賽學生組-最佳影片獎",
    ],
    skill: [
      "版面編排設計",
      "影像處理編輯",
      "電腦繪圖",
      "基礎剪輯",
      "UIUX",
      "PhotoShop",
      "Illustrator",
      "Figma",
      "davinci",
    ],
  },
  {
    id: "55",
    img: "/1/IMG_8389.JPG",
    name: "張芝琳",
    mail: "c8911202@gmail.com",
    profile: "https://linda0983653614.wixsite.com/website",
    experience: ["元智大學資訊傳播系 ISEE Vtuber角色設計"],
    skill: ["2D繪圖", "角色設計", "平面設計"],
  },
  {
    id: "56",
    img: "/5/IMG_7958.JPG",
    name: "邱郁琳",
    mail: "a0909412456@gmail.com",
    profile: "無",
    experience: ["宇大山背柑橘博物館策展員", "第三十屆金犢獎平面類-入圍"],
    skill: ["Procreate", "InDesign", "Adobe Illustrator", "Figma"],
  },
  {
    id: "57",
    img: "/19/IMG_7931.JPG",
    name: "陳品皓",
    mail: "phao2233@gmail.com",
    profile: "https://pinhao_pp8.artstation.com/",
    experience: ["唯晶3D美術實習生"],
    skill: [
      "maya",
      "zbrush",
      "substance",
      "painter",
      "substance deigner",
      "marmoset toolbag",
    ],
  },
  {
    id: "58",
    img: "/1/IMG_8390.JPG",
    name: "趙婉芸",
    mail: "a96004731811@gmail.com",
    profile: "https://www.behance.net/belladodo",
    experience: [
      "擔任元智大學資傳系 陳麗秋教授之助理",
      "玩美文創設計工作室-實習設計助理",
    ],
    skill: ["平面設計", "插畫", "影像處理", "傳統繪畫"],
  },
  {
    id: "59",
    img: "/14/IMG_8499.JPG",
    name: "李美文",
    mail: "limeiwen0213@gmail.com",
    profile: "無",
    experience: [
      "東軟集團股份有限公司見習視覺設計工程師",
      "熱度傳媒短視頻脚本廣告策劃與直播運營",
      "元智大學資傳系實習團隊 ISEE",
    ],
    skill: ["動態影像腳本企劃撰寫", "短影音行銷"],
  },
  {
    id: "60",
    img: "/10/IMG_8488.JPG",
    name: "林若芸",
    mail: "love2001226@gmail.com",
    profile: "無",
    experience: [
      "擔任過2個Youtuber頻道的剪輯師",
      "八藝傳播有限公司實習生",
      "艾瓦奇多媒體有限公司特約剪輯師",
    ],
    skill: ["影視拍攝後製", "Premiere pro", "PhotoShop", "illustrator"],
  },
];
